### ISSUE TITLE
После установки интеграции не открывается мультимедиа браузер

### ISSUE THREAD

**Issue by Vittaly76** [alryaz/hass-yandex-music-browser#14]
После установки интеграции перестал работать мультимедиа-браузер. При его открытии появляется ошибка "Unknown error".
Устанавливал по инструкции.
Интеграция AlexIT установлена, авторизация пройдена.
Данную интеграцию через YAML не настраивал - настраивал через GUI.

Лог:
```
2022-06-17 18:17:20 ERROR (MainThread) [custom_components.yandex_music_browser.default] Default authentication failed: No credentials provided
2022-06-17 18:17:20 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140409586161456] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
File "/config/custom_components/yandex_music_browser/default.py", line 98, in async_get_music_browser
authentication = await async_authenticate_using_config_credentials(hass)
File "/config/custom_components/yandex_music_browser/default.py", line 51, in async_authenticate_using_config_credentials
raise YandexMusicBrowserAuthenticationError("No credentials provided")
custom_components.yandex_music_browser.media_browser.YandexMusicBrowserAuthenticationError: No credentials provided
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1217, in websocket_browse_media
payload = await player.async_browse_media(media_content_type, media_content_id)
File "/config/custom_components/yandex_music_browser/patches/generic.py", line 138, in _patch_generic_async_browse_media
yandex_browse_object = await _patch_root_async_browse_media(
File "/config/custom_components/yandex_music_browser/patches/_base.py", line 19, in _patch_root_async_browse_media
music_browser = await async_get_music_browser(self)
File "/config/custom_components/yandex_music_browser/default.py", line 102, in async_get_music_browser
raise YandexMusicBrowserAuthenticationError(
custom_components.yandex_music_browser.media_browser.YandexMusicBrowserAuthenticationError: Could not authenticate with any of the provided patches
```

**Comment by tjmaru** [comment]
дуль #3 
я решил проблему просто вытащив токен из yandex-station интеграци.
можете попробовать также 
токен искать в файле `.storage/core.config_entries`
```
{
        "entry_id": "longid",
        "version": 1,
        "domain": "yandex_station",
        "title": "your_yandex_login",
        "data": {
          "x_token": "your_token", # <- your tokent copy it to the config
          "music_token": null,
          "cookie": "verylongstring"
        },
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": "your_yandex_login",
        "disabled_by": null
      }
```

here is config
```
yandex_music_browser:
  language: ru
  credentials:
    x_token: "put_your_token_here"
  menu_options:
    - new_releases
    - genres
```

**Comment by Vittaly76** [comment]
> дуль #3 я решил проблему просто вытащив токен из yandex-station интеграци. можете попробовать также токен искать в файле `.storage/core.config_entries`

Спасибо! Но мне не помогло. Вытащил токен из .storage/core.config_entries, но по-прежнему та же ошибка. Вообще, такое впечатление, что автор пока забросил компонент, так что помощи ждать, наверное, не приходится...

**Comment by bisquit2003** [comment]
Все не мог понять почему мультимедиа в ха с такой ошибкой открывалось. Пришлось деактивировать интеграцию и все нормализовалось. Спасибо за совет насчет токена, попробую

**Comment by heibertelf** [comment]
Аналогичная ситуация. Похоже, проект мёртвый.

**Comment by hicom123** [comment]
Используя configuration.yaml
Добавьте **yandex_music_browser:**  куда-нибудь в Ваш файл configuration.yaml (двоеточие на конце обязательно!)
Перезапустите Home Assistant
Пока не довабил в мультимедиа тоже всегда была ошибка.
