### ISSUE TITLE
Error doing job: Future exception was never retrieved - No credentials provided

### ISSUE THREAD

**Issue by klugev303** [alryaz/hass-yandex-music-browser#18]
**_Добрый день!_**
Почему перестала работать интеграция? Что нужно изменить?

Вот лог:

Logger: homeassistant
Source: custom_components/yandex_music_browser/default.py:102
Integration: Браузер Яндекс Музыки ([documentation](https://github.com/alryaz/hass-yandex-music-browser), [issues](https://github.com/alryaz/hass-yandex-music-browser/issues))
First occurred: 15:35:17 (1 occurrences)
Last logged: 15:35:17
Error doing job: Future exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/yandex_music_browser/default.py", line 98, in async_get_music_browser
    authentication = await async_authenticate_using_config_credentials(hass)
  File "/config/custom_components/yandex_music_browser/default.py", line 51, in async_authenticate_using_config_credentials
    raise YandexMusicBrowserAuthenticationError("No credentials provided")
custom_components.yandex_music_browser.media_browser.YandexMusicBrowserAuthenticationError: No credentials provided

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1223, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/yandex_music_browser/patches/generic.py", line 138, in _patch_generic_async_browse_media
    yandex_browse_object = await _patch_root_async_browse_media(
  File "/config/custom_components/yandex_music_browser/patches/_base.py", line 19, in _patch_root_async_browse_media
    music_browser = await async_get_music_browser(self)
  File "/config/custom_components/yandex_music_browser/default.py", line 102, in async_get_music_browser
    raise YandexMusicBrowserAuthenticationError(
custom_components.yandex_music_browser.media_browser.YandexMusicBrowserAuthenticationError: Could not authenticate with any of the provided patches
```

**Comment by alexanderznamensky** [comment]
с декабря не работает

**Comment by klugev303** [comment]
> с декабря не работает

Автор забросил проект?

**Comment by alexanderznamensky** [comment]
это видно по отсутствию обновлений / изменений с прошлого года.
но лучше спросить у самого автора )
но даже в его ТГ-чате - тишина.....
так что думаю, что надеяться не стоит )

**Comment by popsodav** [comment]
Создал PR с обновлением версии библиотеки yandex-music-api.
У меня заработало с версией 2.1.1
https://github.com/alryaz/hass-yandex-music-browser/pull/19

**Comment by klugev303** [comment]
> Создал PR с обновлением версии библиотеки yandex-music-api. У меня заработало с версией 2.1.1 #19

Добрый день!
подскажите как установить тогда Вашу обновлённую версию, не вижу релиза нового..

**Comment by popsodav** [comment]
Пока не вмерджили в основной репозиторий можно сделать так:
1. Удалить старую интеграцию
2. Удалить репозиторий https://github.com/alryaz/hass-yandex-music-browse в HACS
3. Добавить в HACS репозиторий https://github.com/popsodav/hass-yandex-music-browser
4. Установить компонент из добавленного репозитория

**Comment by alexanderznamensky** [comment]
Добрый день.
У меня, к сожалению, не заработало.
Home Assistant 2023.6.2
Supervisor 2023.06.2
Пользовательский интерфейс 20230608.0 - latest
Тип установки Home Assistant Supervised
Raspberry Pi4
 
UPD: В версии 2023.7.* интеграция заработала.
Но, к сожалению, в закладке Мультимедиа для браузера нет ссылки (иконки) Яндекс.Музыка:
![image](https://github.com/alryaz/hass-yandex-music-browser/assets/65254375/39c3f608-70df-4172-9413-e824261a6322)
Для остальных медиа плееров все в порядке:
![image](https://github.com/alryaz/hass-yandex-music-browser/assets/65254375/6339534f-5d41-45fc-8ce6-d8e57e9c9350)

**Comment by Spirituss** [comment]
@popsodav  Попробовал установить, получаю такую ошибку
```
ERROR (MainThread) [custom_components.yandex_music_browser.default] Patch yandex_station failed to authenticate: 'YandexStation' object has no attribute '_added'
```
